### ISSUE TITLE
Better Vim indentation settings

### ISSUE THREAD

**Issue by thorncp** [thorncp/dotfiles#2]
2fa237471cf0548ff265c57737c9b11261930cdf introduced vim-sleuth to configure indentation settings for various languages. Sometimes it doesn't do what I want it to, e.g. when I create a one-off .sql file for a complex-ish query in a Rails app, vim-sleuth has not other .sql files to compare to and picks tabs with a tabstop of 8. I'd like this to default to two spaces. Is that possible?

**Comment by adarsh** [comment]
This SHA seems to be incorrect. Should be 2fa237471cf0548ff265c57737c9b11261930cdf. Nevermind:

It seems like you should be able to do this in an `ftplugin` file, as in `config/nvim/ftplugin/sql.vim`, no? I'm just guessing since it looks like a filetype-specific config.

**Comment by thorncp** [comment]
Good catch on the sha! Yes, I think `ftplugin` is the way to go. When I created this issue I think I had in mind that I wanted to configure vim-sleuth to default to 2 spaces when it didn't know what to do. I still haven't gotten around to looking into that, but I'm thinking of reverting 2fa237471cf0548ff265c57737c9b11261930cdf and going back to being explicit about everything.
